### ISSUE TITLE
Info about compatibility with mobile?

### ISSUE THREAD

**Issue by lucaszanella** [j0r1/JRTPLIB#10] opened 2018-04-15 13:00 UTC
I'm evaluating lots of rtp libraries and therefore can't put effort reading the entire source by now. What would need to be done to make it work on iOS and Android?

Thank you!

**Comment by j0r1** [comment] 2018-04-15 20:40
I've used it on Android, and there are instructions for cross compilation in the [README](https://github.com/j0r1/JRTPLIB/blob/master/README.md). Haven't tried on iOS though, don't know what kind of issues there could arise.

**Comment by lucaszanella** [comment] 2018-04-15 21:54
Nice, I think that's going to work then. Is the android JNI interface possibly open source?  Would economize me a lot of time (what I'm building is open source)

**Comment by j0r1** [comment] 2018-04-16 19:12
I didn't make a JNI interface for it: I used it indirectly by using [emiplib](https://github.com/j0r1/EMIPLIB), which in turn was used in a Qt based program called [AudioReceiver](https://audiotranceiver.appspot.com/)

**Comment by lucaszanella** [comment] 2018-04-20 07:03
I added the cmake to my gradle. I was expecting seeing errors related to android build and versioning but I'm getting an specific error in the code. Could it be a bug in the code? https://stackoverflow.com/questions/49935883/integrating-c-lib-into-gradle-how-to-compile-to-android

(not asking for you to help e integrate the library, but if it's a bug it'd be worth to point)

**Comment by j0r1** [comment] 2018-04-20 07:29
The issue is that e.g. getifaddrs is not recognized; the cmake script tests for this and disables the use if not available. I have no experience combining cmake with gradle I'm afraid.

**Comment by lucaszanella** [comment] 2018-04-20 07:30
That's strange, it should have been disabled then. But I'm going to search about it, thanks

**Comment by j0r1** [comment] 2018-04-24 13:15
Thanks for looking into this; it's now fixed in the master branch

**Closed by j0r1** 2018-04-24 13:15 UTC
